### ISSUE TITLE
No Module error

### ISSUE THREAD

**Issue by gowthamvijay05** [RevoltSecurities/ShodanX#11]
└─# shodanx   
[INFO]: Import Error occured in Module imports due to: No module named 'alive_progress'
[INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page.. 
                                                                                                               

Above mentioned error shown.

**Comment by RevoltSecurities** [comment]
Hi @gowthamvijay05 ,
Please use the command mentioned in below to resolve your problem.

```bash
pip install alive_progress
```

I hope this command will resolve your error.

Kind regards,
@RevoltSecurities
