### ISSUE TITLE
cant run 

### ISSUE THREAD

**Issue by darkcrypt13** [RevoltSecurities/ShodanX#14]
shodanx domain -d tesla.com
[INFO]: Import Error occured in Module imports due to: No module named 'alive_progress'
[INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page..

**Comment by RevoltSecurities** [comment]
Hi @darkcrypt13 ,
Please use command:
```bash
pip install alive_progress
```
This will resolve your issue. 

Kind regards, 
@RevoltSecurities

**Comment by darkcrypt13** [comment]
thx

**Comment by RevoltSecurities** [comment]
great to here, please close the issue if your issue is cleared now
