### ISSUE TITLE
IN WSL2 WITH KALI-LINUX TOOL NOT WORKING

### ISSUE THREAD

**Issue by d4715** [RevoltSecurities/ShodanX#15]
Hello There,

Tool is not working after install.
1)for install 
pip install git+https://github.com/sanjai-AK47/ShodanX

2)shodanx --help

then i got these errors
[INFO]: Import Error occured in Module imports due to: No module named 'alive_progress'
[INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page..

you can check screenshot with this message 
![Capture](https://github.com/user-attachments/assets/e8fda214-993c-4f43-b1f6-3ae9407f13d3)

**Comment by RevoltSecurities** [comment]
Hey @d4715 ,
Please use this command to install the missing package and run the shodanx
without any errors.
```bash
pip install alive_progress
```
Kind regards,
@RevoltSecurities

**Comment by d4715** [comment]
Hello There,
Thank you so much . now tool works fine .
if any doubt occurs so i will ping you back.
Thank you so much 
Thank, 
D4715
