### ISSUE TITLE
How to resolve this type of issue

### ISSUE THREAD

**Issue by shishirs4** [RevoltSecurities/ShodanX#9]
[INFO]: Import Error occured in Module imports due to: attempted relative import with no known parent package
[INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page..

**Comment by RevoltSecurities** [comment]
Hi @shishirs4 , 
please provide information like which command you used, python version because requires latest python version to ne installed.

Kind regards,|
@RevoltSecurities

**Comment by rainman456** [comment]
im having the same issue with shodanx -h

**Comment by RevoltSecurities** [comment]
Hi @rainman456 ,
The issue you are facing because of some packages are missing not because of the installation command so its better to install the missing packages with using `pip install pkg-name` command will install the package and will resolve the error. 

Kind regards, 
@RevoltSecurities

**Comment by Musa-web-apps** [comment]
shodanx -h                                                                                                          [INFO]: Import Error occured in Module imports due to: No module named 'appdirs'                                        [INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page..

**Comment by Musa-web-apps** [comment]
When i ran the command i got that error

shodanx -h 
[INFO]: Import Error occured in Module imports due to: No module named 'appdirs' 

[INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page..

**Comment by shishirs4** [comment]
> When i ran the command i got that error
> 
> shodanx -h [INFO]: Import Error occured in Module imports due to: No module named 'appdirs'
> 
> [INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page..

Install the module with.


pip3 install appdirs

**Comment by RevoltSecurities** [comment]
Hello @shishirs4 ,
Thank you for helping other and @Musa-web-apps  if your issues is over means you can close this issue

kind regards,
@RevoltSecurities
